### ISSUE TITLE
*-pc-windows-msvc Rustc targets are not supported

### ISSUE THREAD

**Issue by denzp** [denzp/rustc-llvm-proxy#1]
Shared LLVM lib exports a very limited amount of symbols for the targets.

**tests fail with**: `Unable to find symbol 'LLVMModuleCreateWithName' in the LLVM shared lib`
**ptx-linker fails with**: `Unable to find symbol 'LLVMContextCreate' in the LLVM shared lib`

If that can't be fixed, we should at least provide a meaningful error message and a hint to use `*-pc-windows-gnu`.

**Comment by bheisler** [comment]
What would it take to fix this?

**Comment by denzp** [comment]
Well, I'm not really sure... Seems like it has something to do about linker during `rustc` compilation process: apparently it strips unused symbols.

I don't have access to the platform, so I can't even debug problem origins. I think it worth creating an issue in Rust repo.

**Comment by bheisler** [comment]
I do have access to Windows (obviously) and I'd be willing to help debug and fix this, but I don't really know what to look for.

**Comment by denzp** [comment]
Can you please try to build rustc from sources and check what symbols [are being exported](https://www.nirsoft.net/utils/dll_export_viewer.html) from `rustc_codegen_llvm-llvm.dll` on different compilation stages? Maybe we would have more symbols in debug build?

This question would probably help us to find out when are they getting stripped (are they?) and adjust the build process.

We are particularly looking for `LLVMModuleCreateWithName` or `LLVMContextCreate` symbols.

**Comment by bheisler** [comment]
In my build the stage 0 build contains the LLVMContextDestroy symbol, but not LLVMContextCreate. That's a bit strange - if something is stripping symbols, why would it strip only one?

I haven't been able to build stage 1 successfully yet (https://github.com/rust-lang/rust/issues/53014). Will add more details when I can - I'm trying a clean rebuild without the `-i` flag to see if that helps.

**Comment by bheisler** [comment]
I think that means we would either have to land a patch to Rust explicitly exposing these functions in that crate (might be difficult, I doubt that's intended to be public API), or somehow make the llvm-proxy work without them. Is that possible?
